# Generated by Django 5.2.8 on 2025-11-14 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('sentence_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('flags', models.BooleanField(default=False)),
                ('confidence_scores', models.IntegerField()),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truthlens.document')),
            ],
        ),
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('correction_id', models.AutoField(primary_key=True, serialize=False)),
                ('suggested_correction', models.TextField()),
                ('reasoning', models.TextField()),
                ('sources', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truthlens.sentence')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truthlens.user'),
        ),
    ]
