# Generated by Django 5.2.8 on 2025-11-15 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truthlens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='sentence_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truthlens.sentence'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truthlens.user'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='truthlens.document'),
        ),
    ]
